### ISSUE TITLE
install on ubuntu 16 using npm

### ISSUE THREAD

**Issue by pmbranco** [sarthology/proGramCLI#4]
I managed to install electronjs on ubuntu 16 using npm.

I am trying to run proGramCli from github, which has clear and simple instructions:

$ git clone https://github.com/sarthology/proGramCLI.git
$ cd proGramCLI
$ npm install
$ npm link
To run it, should be either npm run dev or simply type program

When I do it, I am getting this error:

root@vps47638175:/var/www/mysite# npm start

> programcli@0.0.7 start /var/www/mysite
> electron main/main.js --not-packaged=true

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! programcli@0.0.7 start: `electron main/main.js --not-packaged=true`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the programcli@0.0.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-22T10_38_41_017Z-debug.log
root@vps47638175:/var/www/mysite# npm run dev

root@vps47638175:/var/www/mysite# cat /root/.npm/_logs/2020-01-22T10_38_44_652Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.13.4
3 info using node@v13.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle programcli@0.0.7~predev: programcli@0.0.7
6 info lifecycle programcli@0.0.7~dev: programcli@0.0.7
7 verbose lifecycle programcli@0.0.7~dev: unsafe-perm in lifecycle true
8 verbose lifecycle programcli@0.0.7~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/mysite/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle programcli@0.0.7~dev: CWD: /var/www/mysite
10 silly lifecycle programcli@0.0.7~dev: Args: [ '-c', 'electron main/main.js --not-packaged=true --debug=true' ]
11 silly lifecycle programcli@0.0.7~dev: Returned: code: 1  signal: null
12 info lifecycle programcli@0.0.7~dev: Failed to exec dev script
13 verbose stack Error: programcli@0.0.7 dev: `electron main/main.js --not-packaged=true --debug=true`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid programcli@0.0.7
15 verbose cwd /var/www/mysite
16 verbose Linux 4.4.0
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v13.6.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error programcli@0.0.7 dev: `electron main/main.js --not-packaged=true --debug=true`
22 error Exit status 1
23 error Failed at the programcli@0.0.7 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
Can you provide some help here?

**Comment by TheCrazyMax** [comment]
Upvoting. Same issue here
